//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaywardGamers.KParser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=|DataDirectory|\\KPDatabase.sdf")]
        public string KPDatabaseConnectionString {
            get {
                return ((string)(this["KPDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KPDatabase.sdf")]
        public string DBResourceName {
            get {
                return ((string)(this["DBResourceName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ram")]
        public global::WaywardGamers.KParser.DataSource ParseMode {
            get {
                return ((global::WaywardGamers.KParser.DataSource)(this["ParseMode"]));
            }
            set {
                this["ParseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5678984")]
        public uint MemoryOffset {
            get {
                return ((uint)(this["MemoryOffset"]));
            }
            set {
                this["MemoryOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\PlayOnline\\SquareEnix\\FINAL FANTASY XI\\TEMP")]
        public string FFXILogDirectory {
            get {
                return ((string)(this["FFXILogDirectory"]));
            }
            set {
                this["FFXILogDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParseExistingLogs {
            get {
                return ((bool)(this["ParseExistingLogs"]));
            }
            set {
                this["ParseExistingLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KPDefaultParse.sdf")]
        public string DefaultUnnamedDBFileName {
            get {
                return ((string)(this["DefaultUnnamedDBFileName"]));
            }
            set {
                this["DefaultUnnamedDBFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool dumpDebugTextToFile {
            get {
                return ((bool)(this["dumpDebugTextToFile"]));
            }
            set {
                this["dumpDebugTextToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public uint DaysToRetainErrorLogs {
            get {
                return ((uint)(this["DaysToRetainErrorLogs"]));
            }
            set {
                this["DaysToRetainErrorLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Debug")]
        public global::WaywardGamers.KParser.ErrorLevel ErrorLoggingLevel {
            get {
                return ((global::WaywardGamers.KParser.ErrorLevel)(this["ErrorLoggingLevel"]));
            }
            set {
                this["ErrorLoggingLevel"] = value;
            }
        }
    }
}
