//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaywardGamers.KParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParsedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParsedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaywardGamers.KParser.Resources.ParsedStrings", typeof(ParsedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accession.
        /// </summary>
        public static string Accession {
            get {
                return ResourceManager.GetString("Accession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afflatus Misery.
        /// </summary>
        public static string AfflatusMisery {
            get {
                return ResourceManager.GetString("AfflatusMisery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afflatus Solace.
        /// </summary>
        public static string AfflatusSolace {
            get {
                return ResourceManager.GetString("AfflatusSolace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggressor.
        /// </summary>
        public static string Aggressor {
            get {
                return ResourceManager.GetString("Aggressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alacrity.
        /// </summary>
        public static string Alacrity {
            get {
                return ResourceManager.GetString("Alacrity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altruism.
        /// </summary>
        public static string Altruism {
            get {
                return ResourceManager.GetString("Altruism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string AnyRoll {
            get {
                return ResourceManager.GetString("AnyRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samba.
        /// </summary>
        public static string AnySamba {
            get {
                return ResourceManager.GetString("AnySamba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuet|Madrigal|March|Mambo|Prelude|Ballad|Paeon|Minne|Carol.
        /// </summary>
        public static string AnySong {
            get {
                return ResourceManager.GetString("AnySong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astral Flow.
        /// </summary>
        public static string AstralFlow {
            get {
                return ResourceManager.GetString("AstralFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Lore.
        /// </summary>
        public static string AzureLore {
            get {
                return ResourceManager.GetString("AzureLore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrage.
        /// </summary>
        public static string Barrage {
            get {
                return ResourceManager.GetString("Barrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benediction.
        /// </summary>
        public static string Benediction {
            get {
                return ResourceManager.GetString("Benediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berserk.
        /// </summary>
        public static string Berserk {
            get {
                return ResourceManager.GetString("Berserk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        public static string Bio1 {
            get {
                return ResourceManager.GetString("Bio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio II.
        /// </summary>
        public static string Bio2 {
            get {
                return ResourceManager.GetString("Bio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio III.
        /// </summary>
        public static string Bio3 {
            get {
                return ResourceManager.GetString("Bio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio( I+)?.
        /// </summary>
        public static string BioRegex {
            get {
                return ResourceManager.GetString("BioRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard&apos;s Roll.
        /// </summary>
        public static string BlmRoll {
            get {
                return ResourceManager.GetString("BlmRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Weapon.
        /// </summary>
        public static string BloodWeapon {
            get {
                return ResourceManager.GetString("BloodWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magus&apos;s Roll.
        /// </summary>
        public static string BluRoll {
            get {
                return ResourceManager.GetString("BluRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Step.
        /// </summary>
        public static string BoxStep {
            get {
                return ResourceManager.GetString("BoxStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choral Roll.
        /// </summary>
        public static string BrdRoll {
            get {
                return ResourceManager.GetString("BrdRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beast Roll.
        /// </summary>
        public static string BstRoll {
            get {
                return ResourceManager.GetString("BstRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst Affinity.
        /// </summary>
        public static string BurstAffinity {
            get {
                return ResourceManager.GetString("BurstAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camouflage.
        /// </summary>
        public static string Camouflage {
            get {
                return ResourceManager.GetString("Camouflage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celerity.
        /// </summary>
        public static string Celerity {
            get {
                return ResourceManager.GetString("Celerity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Affinity.
        /// </summary>
        public static string ChainAffinity {
            get {
                return ResourceManager.GetString("ChainAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chainspell.
        /// </summary>
        public static string Chainspell {
            get {
                return ResourceManager.GetString("Chainspell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chakra.
        /// </summary>
        public static string Chakra {
            get {
                return ResourceManager.GetString("Chakra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charm.
        /// </summary>
        public static string Charm {
            get {
                return ResourceManager.GetString("Charm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composure.
        /// </summary>
        public static string Composure {
            get {
                return ResourceManager.GetString("Composure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsair&apos;s Roll.
        /// </summary>
        public static string CorRoll {
            get {
                return ResourceManager.GetString("CorRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterstance.
        /// </summary>
        public static string Counterstance {
            get {
                return ResourceManager.GetString("Counterstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gil|beastmen&apos;s seal|Kindred&apos;s seal|fire crystal|earth crystal|water crystal|wind crystal|ice crystal|thunder crystal|light crystal|dark crystal.
        /// </summary>
        public static string CrystalsAndSealsRegex {
            get {
                return ResourceManager.GetString("CrystalsAndSealsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curaga( [IV]+)?.
        /// </summary>
        public static string CuragaRegex {
            get {
                return ResourceManager.GetString("CuragaRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cure.
        /// </summary>
        public static string Cure1 {
            get {
                return ResourceManager.GetString("Cure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cure II.
        /// </summary>
        public static string Cure2 {
            get {
                return ResourceManager.GetString("Cure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cure III.
        /// </summary>
        public static string Cure3 {
            get {
                return ResourceManager.GetString("Cure3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cure IV.
        /// </summary>
        public static string Cure4 {
            get {
                return ResourceManager.GetString("Cure4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cure V.
        /// </summary>
        public static string Cure5 {
            get {
                return ResourceManager.GetString("Cure5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curing Waltz.
        /// </summary>
        public static string CuringWaltz1 {
            get {
                return ResourceManager.GetString("CuringWaltz1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curing Waltz II.
        /// </summary>
        public static string CuringWaltz2 {
            get {
                return ResourceManager.GetString("CuringWaltz2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curing Waltz III.
        /// </summary>
        public static string CuringWaltz3 {
            get {
                return ResourceManager.GetString("CuringWaltz3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curing Waltz IV.
        /// </summary>
        public static string CuringWaltz4 {
            get {
                return ResourceManager.GetString("CuringWaltz4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Arts.
        /// </summary>
        public static string DarkArts {
            get {
                return ResourceManager.GetString("DarkArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Shot.
        /// </summary>
        public static string DarkShot {
            get {
                return ResourceManager.GetString("DarkShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string Defender {
            get {
                return ResourceManager.GetString("Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desperate Flourish.
        /// </summary>
        public static string DesperateFlourish {
            get {
                return ResourceManager.GetString("DesperateFlourish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia.
        /// </summary>
        public static string Dia1 {
            get {
                return ResourceManager.GetString("Dia1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia II.
        /// </summary>
        public static string Dia2 {
            get {
                return ResourceManager.GetString("Dia2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia III.
        /// </summary>
        public static string Dia3 {
            get {
                return ResourceManager.GetString("Dia3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabolic Eye.
        /// </summary>
        public static string DiabolicEye {
            get {
                return ResourceManager.GetString("DiabolicEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia( I+)?.
        /// </summary>
        public static string DiaRegex {
            get {
                return ResourceManager.GetString("DiaRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispel.
        /// </summary>
        public static string Dispel {
            get {
                return ResourceManager.GetString("Dispel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divine Seal.
        /// </summary>
        public static string DivineSeal {
            get {
                return ResourceManager.GetString("DivineSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divine Waltz.
        /// </summary>
        public static string DivineWaltz {
            get {
                return ResourceManager.GetString("DivineWaltz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancer&apos;s Roll.
        /// </summary>
        public static string DncRoll {
            get {
                return ResourceManager.GetString("DncRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drachen Roll.
        /// </summary>
        public static string DrgRoll {
            get {
                return ResourceManager.GetString("DrgRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos Roll.
        /// </summary>
        public static string DrkRoll {
            get {
                return ResourceManager.GetString("DrkRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eagle Eye Shot.
        /// </summary>
        public static string EagleEyeShot {
            get {
                return ResourceManager.GetString("EagleEyeShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ebullience.
        /// </summary>
        public static string Ebullience {
            get {
                return ResourceManager.GetString("Ebullience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegy.
        /// </summary>
        public static string Elegy {
            get {
                return ResourceManager.GetString("Elegy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Battlefield|Carnage|Massacre) Elegy.
        /// </summary>
        public static string ElegyRegex {
            get {
                return ResourceManager.GetString("ElegyRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemental Seal.
        /// </summary>
        public static string ElementalSeal {
            get {
                return ResourceManager.GetString("ElementalSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equanimity.
        /// </summary>
        public static string Equanimity {
            get {
                return ResourceManager.GetString("Equanimity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase.
        /// </summary>
        public static string Erase {
            get {
                return ResourceManager.GetString("Erase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familiar.
        /// </summary>
        public static string Familiar {
            get {
                return ResourceManager.GetString("Familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fealty.
        /// </summary>
        public static string Fealty {
            get {
                return ResourceManager.GetString("Fealty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feint.
        /// </summary>
        public static string Feint {
            get {
                return ResourceManager.GetString("Feint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focalization.
        /// </summary>
        public static string Focalization {
            get {
                return ResourceManager.GetString("Focalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string Focus {
            get {
                return ResourceManager.GetString("Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fold.
        /// </summary>
        public static string Fold {
            get {
                return ResourceManager.GetString("Fold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footwork.
        /// </summary>
        public static string Footwork {
            get {
                return ResourceManager.GetString("Footwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formless Strikes.
        /// </summary>
        public static string FormlessStrikes {
            get {
                return ResourceManager.GetString("FormlessStrikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gil.
        /// </summary>
        public static string Gil {
            get {
                return ResourceManager.GetString("Gil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasso.
        /// </summary>
        public static string Hasso {
            get {
                return ResourceManager.GetString("Hasso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haste.
        /// </summary>
        public static string Haste {
            get {
                return ResourceManager.GetString("Haste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haste Samba.
        /// </summary>
        public static string HasteSamba {
            get {
                return ResourceManager.GetString("HasteSamba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Breath.
        /// </summary>
        public static string HealingBreath1 {
            get {
                return ResourceManager.GetString("HealingBreath1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Breath II.
        /// </summary>
        public static string HealingBreath2 {
            get {
                return ResourceManager.GetString("HealingBreath2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Breath III.
        /// </summary>
        public static string HealingBreath3 {
            get {
                return ResourceManager.GetString("HealingBreath3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Breeze.
        /// </summary>
        public static string HealingBreeze {
            get {
                return ResourceManager.GetString("HealingBreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healing Waltz.
        /// </summary>
        public static string HealingWaltz {
            get {
                return ResourceManager.GetString("HealingWaltz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hojo: (Ichi|Ni).
        /// </summary>
        public static string HojoRegex {
            get {
                return ResourceManager.GetString("HojoRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundred Fists.
        /// </summary>
        public static string HundredFists {
            get {
                return ResourceManager.GetString("HundredFists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innin.
        /// </summary>
        public static string Innin {
            get {
                return ResourceManager.GetString("Innin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invincible.
        /// </summary>
        public static string Invincible {
            get {
                return ResourceManager.GetString("Invincible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jubaku: (Ichi|Ni).
        /// </summary>
        public static string JubakuRegex {
            get {
                return ResourceManager.GetString("JubakuRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Resort.
        /// </summary>
        public static string LastResort {
            get {
                return ResourceManager.GetString("LastResort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Arts.
        /// </summary>
        public static string LightArts {
            get {
                return ResourceManager.GetString("LightArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Shot.
        /// </summary>
        public static string LightShot {
            get {
                return ResourceManager.GetString("LightShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sword Madrigal.
        /// </summary>
        public static string Madrigal1 {
            get {
                return ResourceManager.GetString("Madrigal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Madrigal.
        /// </summary>
        public static string Madrigal2 {
            get {
                return ResourceManager.GetString("Madrigal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Finale.
        /// </summary>
        public static string MagicFinale {
            get {
                return ResourceManager.GetString("MagicFinale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Fruit.
        /// </summary>
        public static string MagicFruit {
            get {
                return ResourceManager.GetString("MagicFruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manafont.
        /// </summary>
        public static string Manafont {
            get {
                return ResourceManager.GetString("Manafont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifestation.
        /// </summary>
        public static string Manifestation {
            get {
                return ResourceManager.GetString("Manifestation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advancing March.
        /// </summary>
        public static string March1 {
            get {
                return ResourceManager.GetString("March1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory March.
        /// </summary>
        public static string March2 {
            get {
                return ResourceManager.GetString("March2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meditate.
        /// </summary>
        public static string Meditate {
            get {
                return ResourceManager.GetString("Meditate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meikyo Shisui.
        /// </summary>
        public static string MeikyoShisui {
            get {
                return ResourceManager.GetString("MeikyoShisui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mighty Strikes.
        /// </summary>
        public static string MightyStrikes {
            get {
                return ResourceManager.GetString("MightyStrikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijin Gakure.
        /// </summary>
        public static string MijinGakure {
            get {
                return ResourceManager.GetString("MijinGakure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Minuet.
        /// </summary>
        public static string Minuet1 {
            get {
                return ResourceManager.GetString("Minuet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Minuet II.
        /// </summary>
        public static string Minuet2 {
            get {
                return ResourceManager.GetString("Minuet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Minuet III.
        /// </summary>
        public static string Minuet3 {
            get {
                return ResourceManager.GetString("Minuet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Minuet IV.
        /// </summary>
        public static string Minuet4 {
            get {
                return ResourceManager.GetString("Minuet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monk&apos;s Roll.
        /// </summary>
        public static string MnkRoll {
            get {
                return ResourceManager.GetString("MnkRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mug.
        /// </summary>
        public static string Mug {
            get {
                return ResourceManager.GetString("Mug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w+na$.
        /// </summary>
        public static string NaRegex {
            get {
                return ResourceManager.GetString("NaRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja Roll.
        /// </summary>
        public static string NinRoll {
            get {
                return ResourceManager.GetString("NinRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdrive.
        /// </summary>
        public static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overloaded.
        /// </summary>
        public static string Overloaded {
            get {
                return ResourceManager.GetString("Overloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralyze.
        /// </summary>
        public static string Paralyze {
            get {
                return ResourceManager.GetString("Paralyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralyze( I+)?.
        /// </summary>
        public static string ParalyzeRegex {
            get {
                return ResourceManager.GetString("ParalyzeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsimony.
        /// </summary>
        public static string Parsimony {
            get {
                return ResourceManager.GetString("Parsimony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penury.
        /// </summary>
        public static string Penury {
            get {
                return ResourceManager.GetString("Penury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect Dodge.
        /// </summary>
        public static string PerfectDodge {
            get {
                return ResourceManager.GetString("PerfectDodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pianissimo.
        /// </summary>
        public static string Pianissimo {
            get {
                return ResourceManager.GetString("Pianissimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallant&apos;s Roll.
        /// </summary>
        public static string PldRoll {
            get {
                return ResourceManager.GetString("PldRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollen.
        /// </summary>
        public static string Pollen {
            get {
                return ResourceManager.GetString("Pollen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter&apos;s Prelude.
        /// </summary>
        public static string Prelude1 {
            get {
                return ResourceManager.GetString("Prelude1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer&apos;s Prelude.
        /// </summary>
        public static string Prelude2 {
            get {
                return ResourceManager.GetString("Prelude2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppet Roll.
        /// </summary>
        public static string PupRoll {
            get {
                return ResourceManager.GetString("PupRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstep.
        /// </summary>
        public static string Quickstep {
            get {
                return ResourceManager.GetString("Quickstep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise.
        /// </summary>
        public static string Raise {
            get {
                return ResourceManager.GetString("Raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapture.
        /// </summary>
        public static string Rapture {
            get {
                return ResourceManager.GetString("Rapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warlock&apos;s Roll.
        /// </summary>
        public static string RdmRoll {
            get {
                return ResourceManager.GetString("RdmRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regen.
        /// </summary>
        public static string Regen1 {
            get {
                return ResourceManager.GetString("Regen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regen II.
        /// </summary>
        public static string Regen2 {
            get {
                return ResourceManager.GetString("Regen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regen III.
        /// </summary>
        public static string Regen3 {
            get {
                return ResourceManager.GetString("Regen3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunter&apos;s Roll.
        /// </summary>
        public static string RngRoll {
            get {
                return ResourceManager.GetString("RngRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([a-z]+) cell.
        /// </summary>
        public static string SalvageCellRegex {
            get {
                return ResourceManager.GetString("SalvageCellRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samurai Roll.
        /// </summary>
        public static string SamRoll {
            get {
                return ResourceManager.GetString("SamRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar&apos;s Roll.
        /// </summary>
        public static string SchRoll {
            get {
                return ResourceManager.GetString("SchRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seigan.
        /// </summary>
        public static string Seigan {
            get {
                return ResourceManager.GetString("Seigan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekkanoki.
        /// </summary>
        public static string Sekkanoki {
            get {
                return ResourceManager.GetString("Sekkanoki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel.
        /// </summary>
        public static string Sentinel {
            get {
                return ResourceManager.GetString("Sentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpshot.
        /// </summary>
        public static string Sharpshot {
            get {
                return ResourceManager.GetString("Sharpshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow( I+)?.
        /// </summary>
        public static string SlowRegex {
            get {
                return ResourceManager.GetString("SlowRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evoker&apos;s Roll.
        /// </summary>
        public static string SmnRoll {
            get {
                return ResourceManager.GetString("SmnRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snake Eye.
        /// </summary>
        public static string SnakeEye {
            get {
                return ResourceManager.GetString("SnakeEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak Attack.
        /// </summary>
        public static string SneakAttack {
            get {
                return ResourceManager.GetString("SneakAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souleater.
        /// </summary>
        public static string Souleater {
            get {
                return ResourceManager.GetString("Souleater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soul Voice.
        /// </summary>
        public static string SoulVoice {
            get {
                return ResourceManager.GetString("SoulVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Surge.
        /// </summary>
        public static string SpiritSurge {
            get {
                return ResourceManager.GetString("SpiritSurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steal.
        /// </summary>
        public static string Steal {
            get {
                return ResourceManager.GetString("Steal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stun.
        /// </summary>
        public static string Stun {
            get {
                return ResourceManager.GetString("Stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublimation.
        /// </summary>
        public static string Sublimation {
            get {
                return ResourceManager.GetString("Sublimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabula Rasa.
        /// </summary>
        public static string TabulaRasa {
            get {
                return ResourceManager.GetString("TabulaRasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rogue&apos;s Roll.
        /// </summary>
        public static string ThfRoll {
            get {
                return ResourceManager.GetString("ThfRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Eye.
        /// </summary>
        public static string ThirdEye {
            get {
                return ResourceManager.GetString("ThirdEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trance.
        /// </summary>
        public static string Trance {
            get {
                return ResourceManager.GetString("Trance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranquility.
        /// </summary>
        public static string Tranquility {
            get {
                return ResourceManager.GetString("Tranquility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trick Attack.
        /// </summary>
        public static string TrickAttack {
            get {
                return ResourceManager.GetString("TrickAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utsusemi: Ichi.
        /// </summary>
        public static string UtsuIchi {
            get {
                return ResourceManager.GetString("UtsuIchi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utsusemi: Ni.
        /// </summary>
        public static string UtsuNi {
            get {
                return ResourceManager.GetString("UtsuNi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violent Flourish.
        /// </summary>
        public static string ViolentFlourish {
            get {
                return ResourceManager.GetString("ViolentFlourish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warcry.
        /// </summary>
        public static string Warcry {
            get {
                return ResourceManager.GetString("Warcry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter&apos;s Roll.
        /// </summary>
        public static string WarRoll {
            get {
                return ResourceManager.GetString("WarRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer&apos;s Roll.
        /// </summary>
        public static string WhmRoll {
            get {
                return ResourceManager.GetString("WhmRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Card.
        /// </summary>
        public static string WildCard {
            get {
                return ResourceManager.GetString("WildCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wild Carrot.
        /// </summary>
        public static string WildCarrot {
            get {
                return ResourceManager.GetString("WildCarrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yonin.
        /// </summary>
        public static string Yonin {
            get {
                return ResourceManager.GetString("Yonin", resourceCulture);
            }
        }
    }
}
