//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaywardGamers.KParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NonCombat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NonCombat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaywardGamers.KParser.Resources.NonCombat", typeof(NonCombat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Type:.
        /// </summary>
        internal static string ChatPluginCategoryLabel {
            get {
                return ResourceManager.GetString("ChatPluginCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arena.
        /// </summary>
        internal static string ChatPluginChatTypeArena {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeArena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        internal static string ChatPluginChatTypeEcho {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeEcho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote.
        /// </summary>
        internal static string ChatPluginChatTypeEmote {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkshell.
        /// </summary>
        internal static string ChatPluginChatTypeLinkshell {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeLinkshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPC.
        /// </summary>
        internal static string ChatPluginChatTypeNPC {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeNPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string ChatPluginChatTypeParty {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string ChatPluginChatTypeSay {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeSay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shout.
        /// </summary>
        internal static string ChatPluginChatTypeShout {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeShout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell.
        /// </summary>
        internal static string ChatPluginChatTypeTell {
            get {
                return ResourceManager.GetString("ChatPluginChatTypeTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker:.
        /// </summary>
        internal static string ChatPluginSpeakerLabel {
            get {
                return ResourceManager.GetString("ChatPluginSpeakerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatPluginTabName {
            get {
                return ResourceManager.GetString("ChatPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Count &apos;exclude&apos;d Player Kills.
        /// </summary>
        internal static string ExcludedPlayerOption {
            get {
                return ResourceManager.GetString("ExcludedPlayerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Fight Length.
        /// </summary>
        internal static string ExperiencePluginAverageFightLength {
            get {
                return ResourceManager.GetString("ExperiencePluginAverageFightLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Time/Fight.
        /// </summary>
        internal static string ExperiencePluginAverageTimePerFight {
            get {
                return ResourceManager.GetString("ExperiencePluginAverageTimePerFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-5}{1,8}{2,11}{3,9:F2}.
        /// </summary>
        internal static string ExperiencePluginChainFormat {
            get {
                return ResourceManager.GetString("ExperiencePluginChainFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain   Count   Total XP   Avg XP.
        /// </summary>
        internal static string ExperiencePluginChainHeader {
            get {
                return ResourceManager.GetString("ExperiencePluginChainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ExperiencePluginDate {
            get {
                return ResourceManager.GetString("ExperiencePluginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string ExperiencePluginEndTime {
            get {
                return ResourceManager.GetString("ExperiencePluginEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Chains.
        /// </summary>
        internal static string ExperiencePluginExperienceChains {
            get {
                return ResourceManager.GetString("ExperiencePluginExperienceChains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience Rates.
        /// </summary>
        internal static string ExperiencePluginExperienceRates {
            get {
                return ResourceManager.GetString("ExperiencePluginExperienceRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Chain.
        /// </summary>
        internal static string ExperiencePluginHighestChain {
            get {
                return ResourceManager.GetString("ExperiencePluginHighestChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob Listing.
        /// </summary>
        internal static string ExperiencePluginMobListing {
            get {
                return ResourceManager.GetString("ExperiencePluginMobListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob                        Base XP   Number   Avg Fight Time.
        /// </summary>
        internal static string ExperiencePluginMobListingHeader {
            get {
                return ResourceManager.GetString("ExperiencePluginMobListingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Fights.
        /// </summary>
        internal static string ExperiencePluginNumberOfFights {
            get {
                return ResourceManager.GetString("ExperiencePluginNumberOfFights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Duration.
        /// </summary>
        internal static string ExperiencePluginPartyDuration {
            get {
                return ResourceManager.GetString("ExperiencePluginPartyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string ExperiencePluginStartTime {
            get {
                return ResourceManager.GetString("ExperiencePluginStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string ExperiencePluginTabName {
            get {
                return ResourceManager.GetString("ExperiencePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Experience.
        /// </summary>
        internal static string ExperiencePluginTotalExperience {
            get {
                return ResourceManager.GetString("ExperiencePluginTotalExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fight Time.
        /// </summary>
        internal static string ExperiencePluginTotalFightTime {
            get {
                return ResourceManager.GetString("ExperiencePluginTotalFightTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-16} : {1:F2}.
        /// </summary>
        internal static string ExperiencePluginXPListFormatDec {
            get {
                return ResourceManager.GetString("ExperiencePluginXPListFormatDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-16} : {1}.
        /// </summary>
        internal static string ExperiencePluginXPListFormatNum {
            get {
                return ResourceManager.GetString("ExperiencePluginXPListFormatNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-16} : {1:F2} seconds.
        /// </summary>
        internal static string ExperiencePluginXPListFormatSec {
            get {
                return ResourceManager.GetString("ExperiencePluginXPListFormatSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-16} : {1:d}:{2:d2}:{3:d2}.
        /// </summary>
        internal static string ExperiencePluginXPListFormatTime {
            get {
                return ResourceManager.GetString("ExperiencePluginXPListFormatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP/Fight.
        /// </summary>
        internal static string ExperiencePluginXPPerFight {
            get {
                return ResourceManager.GetString("ExperiencePluginXPPerFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP/Hour.
        /// </summary>
        internal static string ExperiencePluginXPPerHour {
            get {
                return ResourceManager.GetString("ExperiencePluginXPPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP/Minute.
        /// </summary>
        internal static string ExperiencePluginXPPerMinute {
            get {
                return ResourceManager.GetString("ExperiencePluginXPPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item                                  Used.
        /// </summary>
        internal static string ItemsPluginGeneralHeader {
            get {
                return ResourceManager.GetString("ItemsPluginGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player:.
        /// </summary>
        internal static string ItemsPluginPlayerLabel {
            get {
                return ResourceManager.GetString("ItemsPluginPlayerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Detail.
        /// </summary>
        internal static string ItemsPluginShowDetail {
            get {
                return ResourceManager.GetString("ItemsPluginShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string ItemsPluginTabName {
            get {
                return ResourceManager.GetString("ItemsPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -No Information-.
        /// </summary>
        internal static string PlayerInfoPluginNoInfo {
            get {
                return ResourceManager.GetString("PlayerInfoPluginNoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Info.
        /// </summary>
        internal static string PlayerInfoPluginTabName {
            get {
                return ResourceManager.GetString("PlayerInfoPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Drops.
        /// </summary>
        internal static string TreasurePluginCellDrops {
            get {
                return ResourceManager.GetString("TreasurePluginCellDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dig and you dig, but find nothing..
        /// </summary>
        internal static string TreasurePluginChocoDiggingFail {
            get {
                return ResourceManager.GetString("TreasurePluginChocoDiggingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^Obtained: {0}\.$.
        /// </summary>
        internal static string TreasurePluginChocoDiggingFormat {
            get {
                return ResourceManager.GetString("TreasurePluginChocoDiggingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears your chocobo found this item with ease..
        /// </summary>
        internal static string TreasurePluginChocoDiggingFWE {
            get {
                return ResourceManager.GetString("TreasurePluginChocoDiggingFWE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution.
        /// </summary>
        internal static string TreasurePluginDistribution {
            get {
                return ResourceManager.GetString("TreasurePluginDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,9} {1,-28} [Average:   {2,8:f2}].
        /// </summary>
        internal static string TreasurePluginDropGilFormat {
            get {
                return ResourceManager.GetString("TreasurePluginDropGilFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,9} {1,-28} [Max #: {2}]  [Items/Kill: {3,6:f3}]  [Drop Rate: {4,8:p2}]  [% of Drops: {5,8:p2}].
        /// </summary>
        internal static string TreasurePluginDropItemFormat {
            get {
                return ResourceManager.GetString("TreasurePluginDropItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped {0,2} items {1,5} times ({2,8:p2}).
        /// </summary>
        internal static string TreasurePluginDroppedItemNTimesFormat {
            get {
                return ResourceManager.GetString("TreasurePluginDroppedItemNTimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,9} [{1,8:p2}] -- {2}.
        /// </summary>
        internal static string TreasurePluginDropRateFormat {
            get {
                return ResourceManager.GetString("TreasurePluginDropRateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Rates.
        /// </summary>
        internal static string TreasurePluginDropRates {
            get {
                return ResourceManager.GetString("TreasurePluginDropRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gil.
        /// </summary>
        internal static string TreasurePluginGil {
            get {
                return ResourceManager.GetString("TreasurePluginGil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to harvest anything..
        /// </summary>
        internal static string TreasurePluginHarvestFail {
            get {
                return ResourceManager.GetString("TreasurePluginHarvestFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your sickle breaks!.
        /// </summary>
        internal static string TreasurePluginHarvestToolBreak {
            get {
                return ResourceManager.GetString("TreasurePluginHarvestToolBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks:.
        /// </summary>
        internal static string TreasurePluginHELMBreaks {
            get {
                return ResourceManager.GetString("TreasurePluginHELMBreaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocobo Digging:.
        /// </summary>
        internal static string TreasurePluginHELMDigging {
            get {
                return ResourceManager.GetString("TreasurePluginHELMDigging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found With Ease:.
        /// </summary>
        internal static string TreasurePluginHELMFoundWithEase {
            get {
                return ResourceManager.GetString("TreasurePluginHELMFoundWithEase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvesting:.
        /// </summary>
        internal static string TreasurePluginHELMHarvesting {
            get {
                return ResourceManager.GetString("TreasurePluginHELMHarvesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging:.
        /// </summary>
        internal static string TreasurePluginHELMLogging {
            get {
                return ResourceManager.GetString("TreasurePluginHELMLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0,-34} {1,5}  [{2,8:p2}].
        /// </summary>
        internal static string TreasurePluginHELMLongLineFormat {
            get {
                return ResourceManager.GetString("TreasurePluginHELMLongLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining/Excavation:.
        /// </summary>
        internal static string TreasurePluginHELMMining {
            get {
                return ResourceManager.GetString("TreasurePluginHELMMining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Digs:.
        /// </summary>
        internal static string TreasurePluginHELMNormalDigs {
            get {
                return ResourceManager.GetString("TreasurePluginHELMNormalDigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string TreasurePluginHELMNothing {
            get {
                return ResourceManager.GetString("TreasurePluginHELMNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0,-34} {1,5}.
        /// </summary>
        internal static string TreasurePluginHELMShortLineFormat {
            get {
                return ResourceManager.GetString("TreasurePluginHELMShortLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items:.
        /// </summary>
        internal static string TreasurePluginHELMTotalItems {
            get {
                return ResourceManager.GetString("TreasurePluginHELMTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tries:.
        /// </summary>
        internal static string TreasurePluginHELMTotalTries {
            get {
                return ResourceManager.GetString("TreasurePluginHELMTotalTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Drops.
        /// </summary>
        internal static string TreasurePluginItemDrops {
            get {
                return ResourceManager.GetString("TreasurePluginItemDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to log anything..
        /// </summary>
        internal static string TreasurePluginLoggingFail {
            get {
                return ResourceManager.GetString("TreasurePluginLoggingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hatchet breaks!.
        /// </summary>
        internal static string TreasurePluginLoggingToolBreak {
            get {
                return ResourceManager.GetString("TreasurePluginLoggingToolBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Rates.
        /// </summary>
        internal static string TreasurePluginLootTypeDropRates {
            get {
                return ResourceManager.GetString("TreasurePluginLootTypeDropRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELM/Chocobo.
        /// </summary>
        internal static string TreasurePluginLootTypeHELM {
            get {
                return ResourceManager.GetString("TreasurePluginLootTypeHELM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot Type.
        /// </summary>
        internal static string TreasurePluginLootTypeMenu {
            get {
                return ResourceManager.GetString("TreasurePluginLootTypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvage.
        /// </summary>
        internal static string TreasurePluginLootTypeSalvage {
            get {
                return ResourceManager.GetString("TreasurePluginLootTypeSalvage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealing.
        /// </summary>
        internal static string TreasurePluginLootTypeStealing {
            get {
                return ResourceManager.GetString("TreasurePluginLootTypeStealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string TreasurePluginLootTypeSummary {
            get {
                return ResourceManager.GetString("TreasurePluginLootTypeSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unable to dig up anything..
        /// </summary>
        internal static string TreasurePluginMiningFail {
            get {
                return ResourceManager.GetString("TreasurePluginMiningFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your pickaxe breaks!.
        /// </summary>
        internal static string TreasurePluginMiningToolBreak {
            get {
                return ResourceManager.GetString("TreasurePluginMiningToolBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drops..
        /// </summary>
        internal static string TreasurePluginNoDrops {
            get {
                return ResourceManager.GetString("TreasurePluginNoDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        internal static string TreasurePluginNothing {
            get {
                return ResourceManager.GetString("TreasurePluginNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of times each group of items dropped..
        /// </summary>
        internal static string TreasurePluginNumberOfTimesDropped {
            get {
                return ResourceManager.GetString("TreasurePluginNumberOfTimesDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Opened {1} times).
        /// </summary>
        internal static string TreasurePluginOpenedNTimesFormat {
            get {
                return ResourceManager.GetString("TreasurePluginOpenedNTimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Crystals and Seals.
        /// </summary>
        internal static string TreasurePluginOptionExcludeCrystals {
            get {
                return ResourceManager.GetString("TreasurePluginOptionExcludeCrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Group Details.
        /// </summary>
        internal static string TreasurePluginOptionGroupMobs {
            get {
                return ResourceManager.GetString("TreasurePluginOptionGroupMobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sickle breaks( in the process)?(\.|!)$.
        /// </summary>
        internal static string TreasurePluginRegexHarvestBreak {
            get {
                return ResourceManager.GetString("TreasurePluginRegexHarvestBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You (successfully )?harvest {0}(, but your sickle breaks( in the process)?)?(.|!)$.
        /// </summary>
        internal static string TreasurePluginRegexHarvestFormat {
            get {
                return ResourceManager.GetString("TreasurePluginRegexHarvestFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((a|an|the) )?(?&lt;item&gt;\w+( \w+)*).
        /// </summary>
        internal static string TreasurePluginRegexItem {
            get {
                return ResourceManager.GetString("TreasurePluginRegexItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string TreasurePluginRegexItemReference {
            get {
                return ResourceManager.GetString("TreasurePluginRegexItemReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hatchet breaks( in the process)?(\.|!)$.
        /// </summary>
        internal static string TreasurePluginRegexLoggingBreak {
            get {
                return ResourceManager.GetString("TreasurePluginRegexLoggingBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You (successfully )?cut off {0}(, but your hatchet breaks( in the process)?)?(.|!)$.
        /// </summary>
        internal static string TreasurePluginRegexLoggingFormat {
            get {
                return ResourceManager.GetString("TreasurePluginRegexLoggingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pickaxe breaks( in the process)?(\.|!)$.
        /// </summary>
        internal static string TreasurePluginRegexMiningBreak {
            get {
                return ResourceManager.GetString("TreasurePluginRegexMiningBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You (successfully )?dig up {0}(, but your pickaxe breaks( in the process)?)?(.|!)$.
        /// </summary>
        internal static string TreasurePluginRegexMiningFormat {
            get {
                return ResourceManager.GetString("TreasurePluginRegexMiningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loot.
        /// </summary>
        internal static string TreasurePluginTabName {
            get {
                return ResourceManager.GetString("TreasurePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Killed {1} times).
        /// </summary>
        internal static string TreasurePluginTimesKilledFormat {
            get {
                return ResourceManager.GetString("TreasurePluginTimesKilledFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treasure Chests.
        /// </summary>
        internal static string TreasurePluginTreasureChests {
            get {
                return ResourceManager.GetString("TreasurePluginTreasureChests", resourceCulture);
            }
        }
    }
}
