//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaywardGamers.KParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Combat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Combat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaywardGamers.KParser.Resources.Combat", typeof(Combat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs Received.
        /// </summary>
        internal static string BuffPluginBuffsReceivedCategory {
            get {
                return ResourceManager.GetString("BuffPluginBuffsReceivedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs Used.
        /// </summary>
        internal static string BuffPluginBuffsUsedCategory {
            get {
                return ResourceManager.GetString("BuffPluginBuffsUsedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string BuffPluginCategoryLabel {
            get {
                return ResourceManager.GetString("BuffPluginCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,15}{1,15}{2,15}.
        /// </summary>
        internal static string BuffPluginIntervalsFormat {
            get {
                return ResourceManager.GetString("BuffPluginIntervalsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7}.
        /// </summary>
        internal static string BuffPluginNumTimesFormat {
            get {
                return ResourceManager.GetString("BuffPluginNumTimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff                Used by             # Times   Min Interval   Max Interval   Avg Interval.
        /// </summary>
        internal static string BuffPluginReceivedHeader {
            get {
                return ResourceManager.GetString("BuffPluginReceivedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string BuffPluginSelf {
            get {
                return ResourceManager.GetString("BuffPluginSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs.
        /// </summary>
        internal static string BuffPluginTabName {
            get {
                return ResourceManager.GetString("BuffPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff                Used on             # Times   Min Interval   Max Interval   Avg Interval.
        /// </summary>
        internal static string BuffPluginUsedHeader {
            get {
                return ResourceManager.GetString("BuffPluginUsedHeader", resourceCulture);
            }
        }
    }
}
