//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaywardGamers.KParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Combat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Combat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaywardGamers.KParser.Resources.Combat", typeof(Combat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs Received.
        /// </summary>
        internal static string BuffPluginBuffsReceivedCategory {
            get {
                return ResourceManager.GetString("BuffPluginBuffsReceivedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs Used.
        /// </summary>
        internal static string BuffPluginBuffsUsedCategory {
            get {
                return ResourceManager.GetString("BuffPluginBuffsUsedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,15}{1,15}{2,15}.
        /// </summary>
        internal static string BuffPluginIntervalsFormat {
            get {
                return ResourceManager.GetString("BuffPluginIntervalsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7}.
        /// </summary>
        internal static string BuffPluginNumTimesFormat {
            get {
                return ResourceManager.GetString("BuffPluginNumTimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff                Used by             # Times   Min Interval   Max Interval   Avg Interval.
        /// </summary>
        internal static string BuffPluginReceivedHeader {
            get {
                return ResourceManager.GetString("BuffPluginReceivedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string BuffPluginSelf {
            get {
                return ResourceManager.GetString("BuffPluginSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs.
        /// </summary>
        internal static string BuffPluginTabName {
            get {
                return ResourceManager.GetString("BuffPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff                Used on             # Times   Min Interval   Max Interval   Avg Interval.
        /// </summary>
        internal static string BuffPluginUsedHeader {
            get {
                return ResourceManager.GetString("BuffPluginUsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff                # Times   # Successful   # No Effect   % Successful.
        /// </summary>
        internal static string DebuffPluginDebuffHeader {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff Mobs.
        /// </summary>
        internal static string DebuffPluginDebuffMobsCategory {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffMobsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff Players.
        /// </summary>
        internal static string DebuffPluginDebuffPlayersCategory {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffPlayersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff              Target              # Times   # Successful   # No Effect   % Successful.
        /// </summary>
        internal static string DebuffPluginDebuffWithTargetsHeader {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffWithTargetsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7:d}{1,15:d}{2,14:d}{3,15:p2}.
        /// </summary>
        internal static string DebuffPluginMobDebuffFormat {
            get {
                return ResourceManager.GetString("DebuffPluginMobDebuffFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,9:d}{1,15:d}{2,14:d}{3,15:p2}.
        /// </summary>
        internal static string DebuffPluginPlayerDebuffFormat {
            get {
                return ResourceManager.GetString("DebuffPluginPlayerDebuffFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuffs.
        /// </summary>
        internal static string DebuffPluginTabName {
            get {
                return ResourceManager.GetString("DebuffPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Ability.
        /// </summary>
        internal static string DefenseFreqPluginAbility {
            get {
                return ResourceManager.GetString("DefenseFreqPluginAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Magic Bursts.
        /// </summary>
        internal static string DefenseFreqPluginMagicBursts {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMagicBursts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Melee.
        /// </summary>
        internal static string DefenseFreqPluginMelee {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Melee Additional Effects.
        /// </summary>
        internal static string DefenseFreqPluginMeleeAE {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMeleeAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Melee Crits.
        /// </summary>
        internal static string DefenseFreqPluginMeleeCrits {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMeleeCrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Range.
        /// </summary>
        internal static string DefenseFreqPluginRange {
            get {
                return ResourceManager.GetString("DefenseFreqPluginRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Range Additional Effects.
        /// </summary>
        internal static string DefenseFreqPluginRangeAE {
            get {
                return ResourceManager.GetString("DefenseFreqPluginRangeAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Range Crits.
        /// </summary>
        internal static string DefenseFreqPluginRangeCrits {
            get {
                return ResourceManager.GetString("DefenseFreqPluginRangeCrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Spells.
        /// </summary>
        internal static string DefenseFreqPluginSpells {
            get {
                return ResourceManager.GetString("DefenseFreqPluginSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Spikes.
        /// </summary>
        internal static string DefenseFreqPluginSpikes {
            get {
                return ResourceManager.GetString("DefenseFreqPluginSpikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Details.
        /// </summary>
        internal static string DefenseFreqPluginTabName {
            get {
                return ResourceManager.GetString("DefenseFreqPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Weaponskills.
        /// </summary>
        internal static string DefenseFreqPluginWeaponskill {
            get {
                return ResourceManager.GetString("DefenseFreqPluginWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Taken.
        /// </summary>
        internal static string DefensePluginCategoryDamageTaken {
            get {
                return ResourceManager.GetString("DefensePluginCategoryDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenses.
        /// </summary>
        internal static string DefensePluginCategoryDefenses {
            get {
                return ResourceManager.GetString("DefensePluginCategoryDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utsusemi.
        /// </summary>
        internal static string DefensePluginCategoryUtsusemi {
            get {
                return ResourceManager.GetString("DefensePluginCategoryUtsusemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,11:p2}{3,10}{4,11:p2}{5,12}{6,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatAbility {
            get {
                return ResourceManager.GetString("DefensePluginFormatAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,7}{2,10:p2}{3,13}{4,14:p2}{5,15}{6,15:p2}.
        /// </summary>
        internal static string DefensePluginFormatActiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginFormatActiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,10}{2,10:p2}{3,11}{5,11}{6,9:f2}{7,7}{8,10}{9,8:f2}{10,10:p2}.
        /// </summary>
        internal static string DefensePluginFormatMelee {
            get {
                return ResourceManager.GetString("DefensePluginFormatMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,9}{2,8}{3,10:f2}{4,11}{5,8}{6,10:f2}{7,10}{8,9}{9,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatOtherMagical {
            get {
                return ResourceManager.GetString("DefensePluginFormatOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,7}{2,13}{3,11}{4,8:f2}{5,10}{6,14}{7,12}{8,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatOtherPhysical {
            get {
                return ResourceManager.GetString("DefensePluginFormatOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,8}{2,11:p2}{3,8}{4,9:p2}{5,10}{6,11:p2}{7,13}{8,14:p2}.
        /// </summary>
        internal static string DefensePluginFormatPassiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginFormatPassiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,10}{2,10:p2}{3,11}{5,11}{6,9:f2}{7,7}{8,10}{9,8:f2}{10,10:p2}.
        /// </summary>
        internal static string DefensePluginFormatRanged {
            get {
                return ResourceManager.GetString("DefensePluginFormatRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,13}{2,16}{3,18}{4,14:p2}{5,17:p2}.
        /// </summary>
        internal static string DefensePluginFormatShadowUse {
            get {
                return ResourceManager.GetString("DefensePluginFormatShadowUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,6}{2,6}{3,11}{4,8:f2}.
        /// </summary>
        internal static string DefensePluginFormatSkillchain {
            get {
                return ResourceManager.GetString("DefensePluginFormatSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,10:p2}{3,9}{4,7}{5,10}{6,10:f2}{7,9}{8,11}{9,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatSpells {
            get {
                return ResourceManager.GetString("DefensePluginFormatSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,10}{2,11:p2}{3,12}{4,12}{5,12}{6,12}{7,12}{8,11}.
        /// </summary>
        internal static string DefensePluginFormatSummary {
            get {
                return ResourceManager.GetString("DefensePluginFormatSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,11}{2,16}{3,12}{4,14}{5,22:f0}.
        /// </summary>
        internal static string DefensePluginFormatUtsuCasting {
            get {
                return ResourceManager.GetString("DefensePluginFormatUtsuCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,11:p2}{3,10}{4,11:p2}{5,12}{6,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatWeaponskill {
            get {
                return ResourceManager.GetString("DefensePluginFormatWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  Abil. Dmg    Abil. %  Hit/Miss    A.Acc %    A.Low/Hi    A.Avg.
        /// </summary>
        internal static string DefensePluginHeaderAbility {
            get {
                return ResourceManager.GetString("DefensePluginHeaderAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Shadow  Shadow %   Anticipate  Anticipate %   Retaliations  Retaliation %.
        /// </summary>
        internal static string DefensePluginHeaderActiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginHeaderActiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Melee Dmg   Melee %   Hit/Miss   M.Low/Hi    M.Avg  #Crit  C.Low/Hi   C.Avg     Crit%.
        /// </summary>
        internal static string DefensePluginHeaderMelee {
            get {
                return ResourceManager.GetString("DefensePluginHeaderMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             M.AE Dmg  # M.AE  M.AE Avg   R.AE Dmg  # R.AE  R.AE Avg   Spk.Dmg  # Spike  Spk.Avg.
        /// </summary>
        internal static string DefensePluginHeaderOtherMagical {
            get {
                return ResourceManager.GetString("DefensePluginHeaderOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             CA.Dmg  CA.Hit/Miss  CA.Low/Hi  CA.Avg   Ret.Dmg  Ret.Hit/Miss  Ret.Low/Hi  Ret.Avg.
        /// </summary>
        internal static string DefensePluginHeaderOtherPhysical {
            get {
                return ResourceManager.GetString("DefensePluginHeaderOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Evasion  Evasion %   Parry  Parry %   Counter  Counter %   Intimidate  Intimidate %.
        /// </summary>
        internal static string DefensePluginHeaderPassiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginHeaderPassiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Range Dmg   Range %   Hit/Miss   R.Low/Hi    R.Avg  #Crit  C.Low/Hi   C.Avg     Crit%.
        /// </summary>
        internal static string DefensePluginHeaderRanged {
            get {
                return ResourceManager.GetString("DefensePluginHeaderRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Shadows Used    Shadows Cast  Shadows Cast(Nin)   Efficiency  Efficiency (Nin).
        /// </summary>
        internal static string DefensePluginHeaderShadowUse {
            get {
                return ResourceManager.GetString("DefensePluginHeaderShadowUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchain          SC Dmg  # SC  SC.Low/Hi  SC.Avg.
        /// </summary>
        internal static string DefensePluginHeaderSkillchain {
            get {
                return ResourceManager.GetString("DefensePluginHeaderSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  Spell Dmg   Spell %  #Spells  #Fail  S.Low/Hi     S.Avg  #MBurst  MB.Low/Hi   MB.Avg.
        /// </summary>
        internal static string DefensePluginHeaderSpells {
            get {
                return ResourceManager.GetString("DefensePluginHeaderSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Total Dmg   Damage %   Melee Dmg   Range Dmg   Abil. Dmg  WSkill Dmg   Spell Dmg  Other Dmg.
        /// </summary>
        internal static string DefensePluginHeaderSummary {
            get {
                return ResourceManager.GetString("DefensePluginHeaderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             :Ichi Cast  :Ichi Finished    :Ni Cast  :Ni Finished    Casting Time (est.).
        /// </summary>
        internal static string DefensePluginHeaderUtsuCasting {
            get {
                return ResourceManager.GetString("DefensePluginHeaderUtsuCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  WSkill Dmg   WSkill %  Hit/Miss   WS.Acc %   WS.Low/Hi   WS.Avg.
        /// </summary>
        internal static string DefensePluginHeaderWeaponskill {
            get {
                return ResourceManager.GetString("DefensePluginHeaderWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string DefensePluginTabName {
            get {
                return ResourceManager.GetString("DefensePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleAbility {
            get {
                return ResourceManager.GetString("DefensePluginTitleAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Defenses.
        /// </summary>
        internal static string DefensePluginTitleActiveDefenses {
            get {
                return ResourceManager.GetString("DefensePluginTitleActiveDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleMelee {
            get {
                return ResourceManager.GetString("DefensePluginTitleMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Magical Damage Taken  (Additional Effects and Spikes).
        /// </summary>
        internal static string DefensePluginTitleOtherMagical {
            get {
                return ResourceManager.GetString("DefensePluginTitleOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Physical Damage Taken  (Counterattacks and Retaliations).
        /// </summary>
        internal static string DefensePluginTitleOtherPhysical {
            get {
                return ResourceManager.GetString("DefensePluginTitleOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive Defenses.
        /// </summary>
        internal static string DefensePluginTitlePassiveDefenses {
            get {
                return ResourceManager.GetString("DefensePluginTitlePassiveDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleRanged {
            get {
                return ResourceManager.GetString("DefensePluginTitleRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Use.
        /// </summary>
        internal static string DefensePluginTitleShadowUse {
            get {
                return ResourceManager.GetString("DefensePluginTitleShadowUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchain Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleSkillchain {
            get {
                return ResourceManager.GetString("DefensePluginTitleSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleSpell {
            get {
                return ResourceManager.GetString("DefensePluginTitleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Taken Summary.
        /// </summary>
        internal static string DefensePluginTitleSummary {
            get {
                return ResourceManager.GetString("DefensePluginTitleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utsusemi Casting.
        /// </summary>
        internal static string DefensePluginTitleUtsuCasting {
            get {
                return ResourceManager.GetString("DefensePluginTitleUtsuCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskill Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleWeaponskill {
            get {
                return ResourceManager.GetString("DefensePluginTitleWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-10}{1,-24}{2,-10}{3,-20}{4,10}{5,11}{6,15}{7,6}{8,8}.
        /// </summary>
        internal static string FightsPluginFightFormat {
            get {
                return ResourceManager.GetString("FightsPluginFightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight #   Enemy                   Killed?   Killed By           Start Time   End Time   Fight Length   Exp   Chain.
        /// </summary>
        internal static string FightsPluginFightHeader {
            get {
                return ResourceManager.GetString("FightsPluginFightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fights.
        /// </summary>
        internal static string FightsPluginTabName {
            get {
                return ResourceManager.GetString("FightsPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FightsPluginUnknownEnemy {
            get {
                return ResourceManager.GetString("FightsPluginUnknownEnemy", resourceCulture);
            }
        }
    }
}
