//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaywardGamers.KParser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Combat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Combat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaywardGamers.KParser.Resources.Combat", typeof(Combat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs Received.
        /// </summary>
        internal static string BuffPluginBuffsReceivedCategory {
            get {
                return ResourceManager.GetString("BuffPluginBuffsReceivedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs Used.
        /// </summary>
        internal static string BuffPluginBuffsUsedCategory {
            get {
                return ResourceManager.GetString("BuffPluginBuffsUsedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,15}{1,15}{2,15}.
        /// </summary>
        internal static string BuffPluginIntervalsFormat {
            get {
                return ResourceManager.GetString("BuffPluginIntervalsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7}.
        /// </summary>
        internal static string BuffPluginNumTimesFormat {
            get {
                return ResourceManager.GetString("BuffPluginNumTimesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff                Used by             # Times   Min Interval   Max Interval   Avg Interval.
        /// </summary>
        internal static string BuffPluginReceivedHeader {
            get {
                return ResourceManager.GetString("BuffPluginReceivedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        internal static string BuffPluginSelf {
            get {
                return ResourceManager.GetString("BuffPluginSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffs.
        /// </summary>
        internal static string BuffPluginTabName {
            get {
                return ResourceManager.GetString("BuffPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buff                Used on             # Times   Min Interval   Max Interval   Avg Interval.
        /// </summary>
        internal static string BuffPluginUsedHeader {
            get {
                return ResourceManager.GetString("BuffPluginUsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rolls.
        /// </summary>
        internal static string CorsairPluginAllRolls {
            get {
                return ResourceManager.GetString("CorsairPluginAllRolls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average:    {0,8:f2}.
        /// </summary>
        internal static string CorsairPluginAverageFormat {
            get {
                return ResourceManager.GetString("CorsairPluginAverageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency of first Double-Up per initial roll.
        /// </summary>
        internal static string CorsairPluginDoubleUpFrequency {
            get {
                return ResourceManager.GetString("CorsairPluginDoubleUpFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        internal static string CorsairPluginFrequency {
            get {
                return ResourceManager.GetString("CorsairPluginFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                    1       2       3       4       5       6       7       8       9      10      11    Bust.
        /// </summary>
        internal static string CorsairPluginFullRollHeader {
            get {
                return ResourceManager.GetString("CorsairPluginFullRollHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage: {0,8:f2}{1,8:f2}{2,8:f2}{3,8:f2}{4,8:f2}{5,8:f2}{6,8:f2}{7,8:f2}{8,8:f2}{9,8:f2}{10,8:f2}{11,8:f2}.
        /// </summary>
        internal static string CorsairPluginLongFloatFormat {
            get {
                return ResourceManager.GetString("CorsairPluginLongFloatFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:  {0,8:d}{1,8:d}{2,8:d}{3,8:d}{4,8:d}{5,8:d}{6,8:d}{7,8:d}{8,8:d}{9,8:d}{10,8:d}{11,8:d}.
        /// </summary>
        internal static string CorsairPluginLongFrequencyFormat {
            get {
                return ResourceManager.GetString("CorsairPluginLongFrequencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Frequency.
        /// </summary>
        internal static string CorsairPluginRollFrequency {
            get {
                return ResourceManager.GetString("CorsairPluginRollFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-11} {1,8:d}{2,8:d}{3,8:d}{4,8:d}{5,8:d}{6,8:d}.
        /// </summary>
        internal static string CorsairPluginShortFormat {
            get {
                return ResourceManager.GetString("CorsairPluginShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage: {0,8:f2}{1,8:f2}{2,8:f2}{3,8:f2}{4,8:f2}{5,8:f2}.
        /// </summary>
        internal static string CorsairPluginShortPercentageFormat {
            get {
                return ResourceManager.GetString("CorsairPluginShortPercentageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial            1       2       3       4       5       6.
        /// </summary>
        internal static string CorsairPluginSingleRollInitialHeader {
            get {
                return ResourceManager.GetString("CorsairPluginSingleRollInitialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:             1       2       3       4       5       6.
        /// </summary>
        internal static string CorsairPluginSingleRollValueHeader {
            get {
                return ResourceManager.GetString("CorsairPluginSingleRollValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corsair.
        /// </summary>
        internal static string CorsairPluginTabName {
            get {
                return ResourceManager.GetString("CorsairPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals.
        /// </summary>
        internal static string CorsairPluginTotals {
            get {
                return ResourceManager.GetString("CorsairPluginTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff                # Times   # Successful   # No Effect   % Successful.
        /// </summary>
        internal static string DebuffPluginDebuffHeader {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff Mobs.
        /// </summary>
        internal static string DebuffPluginDebuffMobsCategory {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffMobsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff Players.
        /// </summary>
        internal static string DebuffPluginDebuffPlayersCategory {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffPlayersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff              Target              # Times   # Successful   # No Effect   % Successful.
        /// </summary>
        internal static string DebuffPluginDebuffWithTargetsHeader {
            get {
                return ResourceManager.GetString("DebuffPluginDebuffWithTargetsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7:d}{1,15:d}{2,14:d}{3,15:p2}.
        /// </summary>
        internal static string DebuffPluginMobDebuffFormat {
            get {
                return ResourceManager.GetString("DebuffPluginMobDebuffFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,9:d}{1,15:d}{2,14:d}{3,15:p2}.
        /// </summary>
        internal static string DebuffPluginPlayerDebuffFormat {
            get {
                return ResourceManager.GetString("DebuffPluginPlayerDebuffFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuffs.
        /// </summary>
        internal static string DebuffPluginTabName {
            get {
                return ResourceManager.GetString("DebuffPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Ability.
        /// </summary>
        internal static string DefenseFreqPluginAbility {
            get {
                return ResourceManager.GetString("DefenseFreqPluginAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Melee Sequence.
        /// </summary>
        internal static string DefenseFreqPluginFullMelee {
            get {
                return ResourceManager.GetString("DefenseFreqPluginFullMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Range Sequence.
        /// </summary>
        internal static string DefenseFreqPluginFullRange {
            get {
                return ResourceManager.GetString("DefenseFreqPluginFullRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Magic Bursts.
        /// </summary>
        internal static string DefenseFreqPluginMagicBursts {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMagicBursts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Melee.
        /// </summary>
        internal static string DefenseFreqPluginMelee {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Melee Additional Effects.
        /// </summary>
        internal static string DefenseFreqPluginMeleeAE {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMeleeAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Melee Crits.
        /// </summary>
        internal static string DefenseFreqPluginMeleeCrits {
            get {
                return ResourceManager.GetString("DefenseFreqPluginMeleeCrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Range.
        /// </summary>
        internal static string DefenseFreqPluginRange {
            get {
                return ResourceManager.GetString("DefenseFreqPluginRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Range Additional Effects.
        /// </summary>
        internal static string DefenseFreqPluginRangeAE {
            get {
                return ResourceManager.GetString("DefenseFreqPluginRangeAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Range Crits.
        /// </summary>
        internal static string DefenseFreqPluginRangeCrits {
            get {
                return ResourceManager.GetString("DefenseFreqPluginRangeCrits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Spells.
        /// </summary>
        internal static string DefenseFreqPluginSpells {
            get {
                return ResourceManager.GetString("DefenseFreqPluginSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Spikes.
        /// </summary>
        internal static string DefenseFreqPluginSpikes {
            get {
                return ResourceManager.GetString("DefenseFreqPluginSpikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense Details.
        /// </summary>
        internal static string DefenseFreqPluginTabName {
            get {
                return ResourceManager.GetString("DefenseFreqPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Weaponskills.
        /// </summary>
        internal static string DefenseFreqPluginWeaponskill {
            get {
                return ResourceManager.GetString("DefenseFreqPluginWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Taken.
        /// </summary>
        internal static string DefensePluginCategoryDamageTaken {
            get {
                return ResourceManager.GetString("DefensePluginCategoryDamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenses.
        /// </summary>
        internal static string DefensePluginCategoryDefenses {
            get {
                return ResourceManager.GetString("DefensePluginCategoryDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utsusemi.
        /// </summary>
        internal static string DefensePluginCategoryUtsusemi {
            get {
                return ResourceManager.GetString("DefensePluginCategoryUtsusemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,11:p2}{3,10}{4,11:p2}{5,12}{6,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatAbility {
            get {
                return ResourceManager.GetString("DefensePluginFormatAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,7}{2,10:p2}{3,13}{4,14:p2}{5,15}{6,15:p2}.
        /// </summary>
        internal static string DefensePluginFormatActiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginFormatActiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,10}{2,10:p2}{3,11}{5,11}{6,9:f2}{7,7}{8,10}{9,8:f2}{10,10:p2}.
        /// </summary>
        internal static string DefensePluginFormatMelee {
            get {
                return ResourceManager.GetString("DefensePluginFormatMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,9}{2,8}{3,10:f2}{4,11}{5,8}{6,10:f2}{7,10}{8,9}{9,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatOtherMagical {
            get {
                return ResourceManager.GetString("DefensePluginFormatOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,7}{2,13}{3,11}{4,8:f2}{5,10}{6,14}{7,12}{8,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatOtherPhysical {
            get {
                return ResourceManager.GetString("DefensePluginFormatOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,8}{2,11:p2}{3,8}{4,9:p2}{5,10}{6,11:p2}{7,13}{8,14:p2}.
        /// </summary>
        internal static string DefensePluginFormatPassiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginFormatPassiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,10}{2,10:p2}{3,11}{5,11}{6,9:f2}{7,7}{8,10}{9,8:f2}{10,10:p2}.
        /// </summary>
        internal static string DefensePluginFormatRanged {
            get {
                return ResourceManager.GetString("DefensePluginFormatRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,13}{2,16}{3,18}{4,14:p2}{5,17:p2}.
        /// </summary>
        internal static string DefensePluginFormatShadowUse {
            get {
                return ResourceManager.GetString("DefensePluginFormatShadowUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,6}{2,6}{3,11}{4,8:f2}.
        /// </summary>
        internal static string DefensePluginFormatSkillchain {
            get {
                return ResourceManager.GetString("DefensePluginFormatSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,10:p2}{3,9}{4,7}{5,10}{6,10:f2}{7,9}{8,11}{9,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatSpells {
            get {
                return ResourceManager.GetString("DefensePluginFormatSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,10}{2,11:p2}{3,12}{4,12}{5,12}{6,12}{7,12}{8,11}.
        /// </summary>
        internal static string DefensePluginFormatSummary {
            get {
                return ResourceManager.GetString("DefensePluginFormatSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,11}{2,16}{3,12}{4,14}{5,22:f0}.
        /// </summary>
        internal static string DefensePluginFormatUtsuCasting {
            get {
                return ResourceManager.GetString("DefensePluginFormatUtsuCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,11:p2}{3,10}{4,11:p2}{5,12}{6,9:f2}.
        /// </summary>
        internal static string DefensePluginFormatWeaponskill {
            get {
                return ResourceManager.GetString("DefensePluginFormatWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  Abil. Dmg    Abil. %  Hit/Miss    A.Acc %    A.Low/Hi    A.Avg.
        /// </summary>
        internal static string DefensePluginHeaderAbility {
            get {
                return ResourceManager.GetString("DefensePluginHeaderAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Shadow  Shadow %   Anticipate  Anticipate %   Retaliations  Retaliation %.
        /// </summary>
        internal static string DefensePluginHeaderActiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginHeaderActiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Melee Dmg   Melee %   Hit/Miss   M.Low/Hi    M.Avg  #Crit  C.Low/Hi   C.Avg     Crit%.
        /// </summary>
        internal static string DefensePluginHeaderMelee {
            get {
                return ResourceManager.GetString("DefensePluginHeaderMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             M.AE Dmg  # M.AE  M.AE Avg   R.AE Dmg  # R.AE  R.AE Avg   Spk.Dmg  # Spike  Spk.Avg.
        /// </summary>
        internal static string DefensePluginHeaderOtherMagical {
            get {
                return ResourceManager.GetString("DefensePluginHeaderOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             CA.Dmg  CA.Hit/Miss  CA.Low/Hi  CA.Avg   Ret.Dmg  Ret.Hit/Miss  Ret.Low/Hi  Ret.Avg.
        /// </summary>
        internal static string DefensePluginHeaderOtherPhysical {
            get {
                return ResourceManager.GetString("DefensePluginHeaderOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Evasion  Evasion %   Parry  Parry %   Counter  Counter %   Intimidate  Intimidate %.
        /// </summary>
        internal static string DefensePluginHeaderPassiveDefense {
            get {
                return ResourceManager.GetString("DefensePluginHeaderPassiveDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Range Dmg   Range %   Hit/Miss   R.Low/Hi    R.Avg  #Crit  C.Low/Hi   C.Avg     Crit%.
        /// </summary>
        internal static string DefensePluginHeaderRanged {
            get {
                return ResourceManager.GetString("DefensePluginHeaderRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Shadows Used    Shadows Cast  Shadows Cast(Nin)   Efficiency  Efficiency (Nin).
        /// </summary>
        internal static string DefensePluginHeaderShadowUse {
            get {
                return ResourceManager.GetString("DefensePluginHeaderShadowUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchain          SC Dmg  # SC  SC.Low/Hi  SC.Avg.
        /// </summary>
        internal static string DefensePluginHeaderSkillchain {
            get {
                return ResourceManager.GetString("DefensePluginHeaderSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  Spell Dmg   Spell %  #Spells  #Fail  S.Low/Hi     S.Avg  #MBurst  MB.Low/Hi   MB.Avg.
        /// </summary>
        internal static string DefensePluginHeaderSpells {
            get {
                return ResourceManager.GetString("DefensePluginHeaderSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             Total Dmg   Damage %   Melee Dmg   Range Dmg   Abil. Dmg  WSkill Dmg   Spell Dmg  Other Dmg.
        /// </summary>
        internal static string DefensePluginHeaderSummary {
            get {
                return ResourceManager.GetString("DefensePluginHeaderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player             :Ichi Cast  :Ichi Finished    :Ni Cast  :Ni Finished    Casting Time (est.).
        /// </summary>
        internal static string DefensePluginHeaderUtsuCasting {
            get {
                return ResourceManager.GetString("DefensePluginHeaderUtsuCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  WSkill Dmg   WSkill %  Hit/Miss   WS.Acc %   WS.Low/Hi   WS.Avg.
        /// </summary>
        internal static string DefensePluginHeaderWeaponskill {
            get {
                return ResourceManager.GetString("DefensePluginHeaderWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string DefensePluginTabName {
            get {
                return ResourceManager.GetString("DefensePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleAbility {
            get {
                return ResourceManager.GetString("DefensePluginTitleAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Defenses.
        /// </summary>
        internal static string DefensePluginTitleActiveDefenses {
            get {
                return ResourceManager.GetString("DefensePluginTitleActiveDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleMelee {
            get {
                return ResourceManager.GetString("DefensePluginTitleMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Magical Damage Taken  (Additional Effects and Spikes).
        /// </summary>
        internal static string DefensePluginTitleOtherMagical {
            get {
                return ResourceManager.GetString("DefensePluginTitleOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Physical Damage Taken  (Counterattacks and Retaliations).
        /// </summary>
        internal static string DefensePluginTitleOtherPhysical {
            get {
                return ResourceManager.GetString("DefensePluginTitleOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive Defenses.
        /// </summary>
        internal static string DefensePluginTitlePassiveDefenses {
            get {
                return ResourceManager.GetString("DefensePluginTitlePassiveDefenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleRanged {
            get {
                return ResourceManager.GetString("DefensePluginTitleRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Use.
        /// </summary>
        internal static string DefensePluginTitleShadowUse {
            get {
                return ResourceManager.GetString("DefensePluginTitleShadowUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchain Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleSkillchain {
            get {
                return ResourceManager.GetString("DefensePluginTitleSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleSpell {
            get {
                return ResourceManager.GetString("DefensePluginTitleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Taken Summary.
        /// </summary>
        internal static string DefensePluginTitleSummary {
            get {
                return ResourceManager.GetString("DefensePluginTitleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utsusemi Casting.
        /// </summary>
        internal static string DefensePluginTitleUtsuCasting {
            get {
                return ResourceManager.GetString("DefensePluginTitleUtsuCasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskill Damage Taken.
        /// </summary>
        internal static string DefensePluginTitleWeaponskill {
            get {
                return ResourceManager.GetString("DefensePluginTitleWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,12}{2,12}{3,11}.
        /// </summary>
        internal static string DPMPluginBattleFormat {
            get {
                return ResourceManager.GetString("DPMPluginBattleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mob                  Fight Start   Fight End   Duration.
        /// </summary>
        internal static string DPMPluginBattleHeader {
            get {
                return ResourceManager.GetString("DPMPluginBattleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative Damage Per Minute.
        /// </summary>
        internal static string DPMPluginCumulatePerMinute {
            get {
                return ResourceManager.GetString("DPMPluginCumulatePerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage in the first minute.
        /// </summary>
        internal static string DPMPluginDamageInFirstMinute {
            get {
                return ResourceManager.GetString("DPMPluginDamageInFirstMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage in the last minute.
        /// </summary>
        internal static string DPMPluginDamageInLastMinute {
            get {
                return ResourceManager.GetString("DPMPluginDamageInLastMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage in the previous minute.
        /// </summary>
        internal static string DPMPluginDamageInPrevMinute {
            get {
                return ResourceManager.GetString("DPMPluginDamageInPrevMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,11}{2,12:f2}{3,12:f2}{4,12:f2}{5,11:f2}{6,9:f2}{7,12:f2}{8,12:f2}.
        /// </summary>
        internal static string DPMPluginDataFormat {
            get {
                return ResourceManager.GetString("DPMPluginDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               Start Time   Melee DPM   Range DPM   Magic DPM   Abil DPM   WS DPM   Other DPM   Total DPM.
        /// </summary>
        internal static string DPMPluginDataHeader {
            get {
                return ResourceManager.GetString("DPMPluginDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only process single mobs at this time..
        /// </summary>
        internal static string DPMPluginOnlySingleMobs {
            get {
                return ResourceManager.GetString("DPMPluginOnlySingleMobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight Summary.
        /// </summary>
        internal static string DPMPluginSummaryTitle {
            get {
                return ResourceManager.GetString("DPMPluginSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage/Minute.
        /// </summary>
        internal static string DPMPluginTabName {
            get {
                return ResourceManager.GetString("DPMPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack Speed.
        /// </summary>
        internal static string EnfeeblePluginCategoryAttackSpeed {
            get {
                return ResourceManager.GetString("EnfeeblePluginCategoryAttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfeeble Durations.
        /// </summary>
        internal static string EnfeeblePluginCategoryDurations {
            get {
                return ResourceManager.GetString("EnfeeblePluginCategoryDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralyze.
        /// </summary>
        internal static string EnfeeblePluginCategoryParalyze {
            get {
                return ResourceManager.GetString("EnfeeblePluginCategoryParalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Moves.
        /// </summary>
        internal static string EnfeeblePluginCategoryTPMoves {
            get {
                return ResourceManager.GetString("EnfeeblePluginCategoryTPMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,12:d}{1,19}{2,17}.
        /// </summary>
        internal static string EnfeeblePluginFormatDurations {
            get {
                return ResourceManager.GetString("EnfeeblePluginFormatDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,8:d}{1,21}{2,21}{3,29}{4,17:p2}.
        /// </summary>
        internal static string EnfeeblePluginFormatParalyze {
            get {
                return ResourceManager.GetString("EnfeeblePluginFormatParalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,8:d}{1,16}{2,18}{3,13}{4,18:f2}{5,13}{6,18:f2}.
        /// </summary>
        internal static string EnfeeblePluginFormatSpeed {
            get {
                return ResourceManager.GetString("EnfeeblePluginFormatSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7:d}{1,16}{2,14}{3,20}{4,25:f1}.
        /// </summary>
        internal static string EnfeeblePluginFormatTPMoves {
            get {
                return ResourceManager.GetString("EnfeeblePluginFormatTPMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuff               #Successful     Total Duration     Avg Duration.
        /// </summary>
        internal static string EnfeeblePluginHeaderDurations {
            get {
                return ResourceManager.GetString("EnfeeblePluginHeaderDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fights      # Paralyze Cast    # Times Paralyzed    Max # Paralyzable Actions    Paralyze Rate.
        /// </summary>
        internal static string EnfeeblePluginHeaderParalyze {
            get {
                return ResourceManager.GetString("EnfeeblePluginHeaderParalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                               (Slow)       (Slow)            (Normal)     (Normal).
        /// </summary>
        internal static string EnfeeblePluginHeaderSpeed1 {
            get {
                return ResourceManager.GetString("EnfeeblePluginHeaderSpeed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Fights    # Slows Cast     # Mobs Slowed    # Actions    Attacks/Minute    # Actions    Attacks/Minute.
        /// </summary>
        internal static string EnfeeblePluginHeaderSpeed2 {
            get {
                return ResourceManager.GetString("EnfeeblePluginHeaderSpeed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Moves      Total Time      # Fights    Avg Time/TP Move      Avg TP Moves/Minute.
        /// </summary>
        internal static string EnfeeblePluginHeaderTPMoves {
            get {
                return ResourceManager.GetString("EnfeeblePluginHeaderTPMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfeebling.
        /// </summary>
        internal static string EnfeeblePluginTabName {
            get {
                return ResourceManager.GetString("EnfeeblePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enfeeble Durations.
        /// </summary>
        internal static string EnfeeblePluginTitleDurations {
            get {
                return ResourceManager.GetString("EnfeeblePluginTitleDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paralyzed Actions.
        /// </summary>
        internal static string EnfeeblePluginTitleParalyze {
            get {
                return ResourceManager.GetString("EnfeeblePluginTitleParalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowed Actions.
        /// </summary>
        internal static string EnfeeblePluginTitleSpeed {
            get {
                return ResourceManager.GetString("EnfeeblePluginTitleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Moves.
        /// </summary>
        internal static string EnfeeblePluginTitleTPMoves {
            get {
                return ResourceManager.GetString("EnfeeblePluginTitleTPMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string ExtraAttPluginAttack {
            get {
                return ResourceManager.GetString("ExtraAttPluginAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacks.
        /// </summary>
        internal static string ExtraAttPluginAttacks {
            get {
                return ResourceManager.GetString("ExtraAttPluginAttacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base # of Attacks:.
        /// </summary>
        internal static string ExtraAttPluginBaseAttNumLabel {
            get {
                return ResourceManager.GetString("ExtraAttPluginBaseAttNumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckets (Attack intervals at 0.5 sec resolution):.
        /// </summary>
        internal static string ExtraAttPluginBucketsHeader {
            get {
                return ResourceManager.GetString("ExtraAttPluginBucketsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ExtraAttPluginCategory1 {
            get {
                return ResourceManager.GetString("ExtraAttPluginCategory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ExtraAttPluginCategory2 {
            get {
                return ResourceManager.GetString("ExtraAttPluginCategory2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string ExtraAttPluginCategoryAuto {
            get {
                return ResourceManager.GetString("ExtraAttPluginCategoryAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,16}{2,18}{3,17}{4,19}.
        /// </summary>
        internal static string ExtraAttPluginFormatMain1 {
            get {
                return ResourceManager.GetString("ExtraAttPluginFormatMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{2,12}{3,14}{4,14}{5,14}{6,16}.
        /// </summary>
        internal static string ExtraAttPluginFormatMain2 {
            get {
                return ResourceManager.GetString("ExtraAttPluginFormatMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,21}{2,17:p2}{3,24}{4,24}.
        /// </summary>
        internal static string ExtraAttPluginFormatMain3 {
            get {
                return ResourceManager.GetString("ExtraAttPluginFormatMain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               # Melee Attacks    # Melee Rounds    Attacks/Round    # Extra Attacks.
        /// </summary>
        internal static string ExtraAttPluginHeaderMain1 {
            get {
                return ResourceManager.GetString("ExtraAttPluginHeaderMain1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               # +1 Rounds   # +2 Rounds   # +3 Rounds   # +4 Rounds    # &gt;+4 Rounds.
        /// </summary>
        internal static string ExtraAttPluginHeaderMain2 {
            get {
                return ResourceManager.GetString("ExtraAttPluginHeaderMain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               # MultiAttack Rounds    MultiAttack %     Kills w/Min Attacks    Kills w/&lt;Min Attacks.
        /// </summary>
        internal static string ExtraAttPluginHeaderMain3 {
            get {
                return ResourceManager.GetString("ExtraAttPluginHeaderMain3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        internal static string ExtraAttPluginMainSectionTitle {
            get {
                return ResourceManager.GetString("ExtraAttPluginMainSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted while a parse is running..
        /// </summary>
        internal static string ExtraAttPluginRestrictedWarning {
            get {
                return ResourceManager.GetString("ExtraAttPluginRestrictedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,10}{2,20}{3,20:p2}.
        /// </summary>
        internal static string ExtraAttPluginSectionKicksFormat {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionKicksFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               Footwork?    # Rounds w/Kicks    Kick Attack Rate.
        /// </summary>
        internal static string ExtraAttPluginSectionKicksHeader {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionKicksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-attacks per round (Kicks):.
        /// </summary>
        internal static string ExtraAttPluginSectionKicksTitle {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionKicksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,17}{2,11:p2}{3,12:p2}{4,21}{5,11:p2}{6,12:p2}.
        /// </summary>
        internal static string ExtraAttPluginSectionMultiAttacksFormat {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionMultiAttacksFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               # Double Attacks    DA Rate    Perc. DA     # Triple Attacks    TA Rate    Perc. TA.
        /// </summary>
        internal static string ExtraAttPluginSectionMultiAttacksHeader {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionMultiAttacksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-attacks per attack (2x/3x):.
        /// </summary>
        internal static string ExtraAttPluginSectionMultiAttacksTitle {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionMultiAttacksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat As:.
        /// </summary>
        internal static string ExtraAttPluginSectionTreatAs {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionTreatAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,30:p2}{2,31:p2}.
        /// </summary>
        internal static string ExtraAttPluginSectionZanshinAccFormat {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionZanshinAccFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               Acc. Rate of First Attacks    Acc. Rate of Second Attacks.
        /// </summary>
        internal static string ExtraAttPluginSectionZanshinAccHeader {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionZanshinAccHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,23}{2,23}{3,21:p2}.
        /// </summary>
        internal static string ExtraAttPluginSectionZanshinFormat {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionZanshinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               # Missed First Attacks    # DA w/Missed First   Possible Zanshin %.
        /// </summary>
        internal static string ExtraAttPluginSectionZanshinHeader {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionZanshinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-attacks per attack (Zanshin):.
        /// </summary>
        internal static string ExtraAttPluginSectionZanshinTitle {
            get {
                return ResourceManager.GetString("ExtraAttPluginSectionZanshinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Attacks.
        /// </summary>
        internal static string ExtraAttPluginTabName {
            get {
                return ResourceManager.GetString("ExtraAttPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncorrected Details.
        /// </summary>
        internal static string ExtraAttPluginUncorrectedDetails {
            get {
                return ResourceManager.GetString("ExtraAttPluginUncorrectedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-10}{1,-24}{2,-10}{3,-20}{4,10}{5,11}{6,15}{7,6}{8,8}.
        /// </summary>
        internal static string FightsPluginFightFormat {
            get {
                return ResourceManager.GetString("FightsPluginFightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight #   Enemy                   Killed?   Killed By           Start Time   End Time   Fight Length   Exp   Chain.
        /// </summary>
        internal static string FightsPluginFightHeader {
            get {
                return ResourceManager.GetString("FightsPluginFightHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fights.
        /// </summary>
        internal static string FightsPluginTabName {
            get {
                return ResourceManager.GetString("FightsPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Unknown-.
        /// </summary>
        internal static string FightsPluginUnknownEnemy {
            get {
                return ResourceManager.GetString("FightsPluginUnknownEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Counters.
        /// </summary>
        internal static string OffenseFreqPluginCounters {
            get {
                return ResourceManager.GetString("OffenseFreqPluginCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Retaliations.
        /// </summary>
        internal static string OffenseFreqPluginRetaliations {
            get {
                return ResourceManager.GetString("OffenseFreqPluginRetaliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense Detail.
        /// </summary>
        internal static string OffenseFreqTabName {
            get {
                return ResourceManager.GetString("OffenseFreqTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities.
        /// </summary>
        internal static string OffensePluginCategoryAbility {
            get {
                return ResourceManager.GetString("OffensePluginCategoryAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string OffensePluginCategoryMelee {
            get {
                return ResourceManager.GetString("OffensePluginCategoryMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OffensePluginCategoryOther {
            get {
                return ResourceManager.GetString("OffensePluginCategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string OffensePluginCategoryRanged {
            get {
                return ResourceManager.GetString("OffensePluginCategoryRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchains.
        /// </summary>
        internal static string OffensePluginCategorySkillchain {
            get {
                return ResourceManager.GetString("OffensePluginCategorySkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spells.
        /// </summary>
        internal static string OffensePluginCategorySpell {
            get {
                return ResourceManager.GetString("OffensePluginCategorySpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string OffensePluginCategorySummary {
            get {
                return ResourceManager.GetString("OffensePluginCategorySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskills.
        /// </summary>
        internal static string OffensePluginCategoryWeaponskill {
            get {
                return ResourceManager.GetString("OffensePluginCategoryWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,11:p2}{3,10}{4,11:p2}{5,12}{6,9:f2}.
        /// </summary>
        internal static string OffensePluginFormatAbility {
            get {
                return ResourceManager.GetString("OffensePluginFormatAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,10}{2,10:p2}{3,11}{4,10:p2}{5,10}{6,9:f2}{7,7}{8,10}{9,8:f2}{10,10:p2}.
        /// </summary>
        internal static string OffensePluginFormatMelee {
            get {
                return ResourceManager.GetString("OffensePluginFormatMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,9}{2,8}{3,10:f2}{4,11}{5,8}{6,10:f2}{7,10}{8,9}{9,9:f2}.
        /// </summary>
        internal static string OffensePluginFormatOtherMagical {
            get {
                return ResourceManager.GetString("OffensePluginFormatOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,7}{2,13}{3,11}{4,8:f2}{5,10}{6,14}{7,12}{8,9:f2}.
        /// </summary>
        internal static string OffensePluginFormatOtherPhysical {
            get {
                return ResourceManager.GetString("OffensePluginFormatOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,10}{2,10:p2}{3,11}{4,10:p2}{5,10}{6,9:f2}{7,7}{8,10}{9,8:f2}{10,10:p2}.
        /// </summary>
        internal static string OffensePluginFormatRanged {
            get {
                return ResourceManager.GetString("OffensePluginFormatRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,6}{2,6}{3,11}{4,8:f2}.
        /// </summary>
        internal static string OffensePluginFormatSkillchain {
            get {
                return ResourceManager.GetString("OffensePluginFormatSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,10:p2}{3,9}{4,7}{5,10}{6,10:f2}{7,9}{8,11}{9,9:f2}.
        /// </summary>
        internal static string OffensePluginFormatSpell {
            get {
                return ResourceManager.GetString("OffensePluginFormatSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,10}{2,11:p2}{3,12}{4,12}{5,12}{6,12}{7,12}{8,11}.
        /// </summary>
        internal static string OffensePluginFormatSummary {
            get {
                return ResourceManager.GetString("OffensePluginFormatSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-23}{1,10}{2,11:p2}{3,10}{4,11:p2}{5,12}{6,9:f2}.
        /// </summary>
        internal static string OffensePluginFormatWeaponskill {
            get {
                return ResourceManager.GetString("OffensePluginFormatWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  Abil. Dmg    Abil. %  Hit/Miss    A.Acc %    A.Low/Hi    A.Avg.
        /// </summary>
        internal static string OffensePluginHeaderAbility {
            get {
                return ResourceManager.GetString("OffensePluginHeaderAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player            Melee Dmg   Melee %   Hit/Miss   M.Acc %  M.Low/Hi    M.Avg  #Crit  C.Low/Hi   C.Avg     Crit%.
        /// </summary>
        internal static string OffensePluginHeaderMelee {
            get {
                return ResourceManager.GetString("OffensePluginHeaderMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player            M.AE Dmg  # M.AE  M.AE Avg   R.AE Dmg  # R.AE  R.AE Avg   Spk.Dmg  # Spike  Spk.Avg.
        /// </summary>
        internal static string OffensePluginHeaderOtherMagical {
            get {
                return ResourceManager.GetString("OffensePluginHeaderOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player            CA.Dmg  CA.Hit/Miss  CA.Low/Hi  CA.Avg   Ret.Dmg  Ret.Hit/Miss  Ret.Low/Hi  Ret.Avg.
        /// </summary>
        internal static string OffensePluginHeaderOtherPhysical {
            get {
                return ResourceManager.GetString("OffensePluginHeaderOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player            Range Dmg   Range %   Hit/Miss   R.Acc %  R.Low/Hi    R.Avg  #Crit  C.Low/Hi   C.Avg     Crit%.
        /// </summary>
        internal static string OffensePluginHeaderRanged {
            get {
                return ResourceManager.GetString("OffensePluginHeaderRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchain          SC Dmg  # SC  SC.Low/Hi  SC.Avg.
        /// </summary>
        internal static string OffensePluginHeaderSkillchain {
            get {
                return ResourceManager.GetString("OffensePluginHeaderSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                  Spell Dmg   Spell %  #Spells  #Fail  S.Low/Hi     S.Avg  #MBurst  MB.Low/Hi   MB.Avg.
        /// </summary>
        internal static string OffensePluginHeaderSpell {
            get {
                return ResourceManager.GetString("OffensePluginHeaderSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               Total Dmg   Damage %   Melee Dmg   Range Dmg   Abil. Dmg  WSkill Dmg   Spell Dmg  Other Dmg.
        /// </summary>
        internal static string OffensePluginHeaderSummary {
            get {
                return ResourceManager.GetString("OffensePluginHeaderSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player                 WSkill Dmg   WSkill %  Hit/Miss   WS.Acc %   WS.Low/Hi   WS.Avg.
        /// </summary>
        internal static string OffensePluginHeaderWeaponskill {
            get {
                return ResourceManager.GetString("OffensePluginHeaderWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offense.
        /// </summary>
        internal static string OffensePluginTabName {
            get {
                return ResourceManager.GetString("OffensePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Damage.
        /// </summary>
        internal static string OffensePluginTitleAbility {
            get {
                return ResourceManager.GetString("OffensePluginTitleAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee Damage.
        /// </summary>
        internal static string OffensePluginTitleMelee {
            get {
                return ResourceManager.GetString("OffensePluginTitleMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Magical Damage  (Additional Effects and Spikes).
        /// </summary>
        internal static string OffensePluginTitleOtherMagical {
            get {
                return ResourceManager.GetString("OffensePluginTitleOtherMagical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Physical Damage  (Counterattacks and Retaliations).
        /// </summary>
        internal static string OffensePluginTitleOtherPhysical {
            get {
                return ResourceManager.GetString("OffensePluginTitleOtherPhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged Damage.
        /// </summary>
        internal static string OffensePluginTitleRanged {
            get {
                return ResourceManager.GetString("OffensePluginTitleRanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillchain Damage.
        /// </summary>
        internal static string OffensePluginTitleSkillchain {
            get {
                return ResourceManager.GetString("OffensePluginTitleSkillchain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Damage.
        /// </summary>
        internal static string OffensePluginTitleSpell {
            get {
                return ResourceManager.GetString("OffensePluginTitleSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Summary.
        /// </summary>
        internal static string OffensePluginTitleSummary {
            get {
                return ResourceManager.GetString("OffensePluginTitleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskill Damage.
        /// </summary>
        internal static string OffensePluginTitleWeaponskill {
            get {
                return ResourceManager.GetString("OffensePluginTitleWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,12:f2}{2,13:f2}{3,11:f2}{4,13:f2}{5,13:f2}{6,13:f2}.
        /// </summary>
        internal static string PerformancePluginDPSFormat {
            get {
                return ResourceManager.GetString("PerformancePluginDPSFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player              Melee DPS   Ranged DPS     WS DPS    Magic DPS    Other DPS    Total DPS.
        /// </summary>
        internal static string PerformancePluginDPSHeader {
            get {
                return ResourceManager.GetString("PerformancePluginDPSHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Per Second.
        /// </summary>
        internal static string PerformancePluginDPSTitle {
            get {
                return ResourceManager.GetString("PerformancePluginDPSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-18}{1,21}.
        /// </summary>
        internal static string PerformancePluginOverallFormat {
            get {
                return ResourceManager.GetString("PerformancePluginOverallFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total # Fights      Total Fights Length.
        /// </summary>
        internal static string PerformancePluginOverallHeader {
            get {
                return ResourceManager.GetString("PerformancePluginOverallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall.
        /// </summary>
        internal static string PerformancePluginOverallTitle {
            get {
                return ResourceManager.GetString("PerformancePluginOverallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,16}{2,18:p2}.
        /// </summary>
        internal static string PerformancePluginParticipateFightsFormat {
            get {
                return ResourceManager.GetString("PerformancePluginParticipateFightsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player           Number of fights   % Participation.
        /// </summary>
        internal static string PerformancePluginParticipateFightsHeader {
            get {
                return ResourceManager.GetString("PerformancePluginParticipateFightsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,19}{2,22:p2}{3,17}{4,17:p2}{5,17:p2}.
        /// </summary>
        internal static string PerformancePluginParticipateTimeFormat {
            get {
                return ResourceManager.GetString("PerformancePluginParticipateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player           Total time fighting   Total fight lengths   Avg Time/Fight   % Fights&apos; Time   % Overall Time.
        /// </summary>
        internal static string PerformancePluginParticipateTimeHeader {
            get {
                return ResourceManager.GetString("PerformancePluginParticipateTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Participation (Offensive).
        /// </summary>
        internal static string PerformancePluginParticipateTitle {
            get {
                return ResourceManager.GetString("PerformancePluginParticipateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string PerformancePluginTabName {
            get {
                return ResourceManager.GetString("PerformancePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Curing.
        /// </summary>
        internal static string RecoveryPluginCategoryAvgCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginCategoryAvgCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curing.
        /// </summary>
        internal static string RecoveryPluginCategoryCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginCategoryCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string RecoveryPluginCategoryRecovery {
            get {
                return ResourceManager.GetString("RecoveryPluginCategoryRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,10:f2}{2,13:f2}{3,13:f2}{4,13:f2}{5,13:f2}{6,13:f2}{7,14:f2}.
        /// </summary>
        internal static string RecoveryPluginFormatAvgCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginFormatAvgCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,9}{2,12}{3,7}{4,6}{5,6}{6,6}{7,6}{8,9}{9,7}{10,7}{11,7}.
        /// </summary>
        internal static string RecoveryPluginFormatCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginFormatCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-17}{1,9}{2,13}{3,11}{4,9}{5,11}{6,11}.
        /// </summary>
        internal static string RecoveryPluginFormatRecovery {
            get {
                return ResourceManager.GetString("RecoveryPluginFormatRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player           Avg Cure 1   Avg Cure 2   Avg Cure 3   Avg Cure 4   Avg Cure 5   Avg Curaga   Avg Ability.
        /// </summary>
        internal static string RecoveryPluginHeaderAvgCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginHeaderAvgCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player           Cured (Sp)  Cured (Ab)  C.1s  C.2s  C.3s  C.4s  C.5s  Curagas  Rg.1s  Rg.2s  Rg.3s.
        /// </summary>
        internal static string RecoveryPluginHeaderCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginHeaderCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player           Dmg Taken   HP Drained   HP Cured   #Regen   #Regen 2   #Regen 3.
        /// </summary>
        internal static string RecoveryPluginHeaderRecovery {
            get {
                return ResourceManager.GetString("RecoveryPluginHeaderRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery.
        /// </summary>
        internal static string RecoveryPluginTabName {
            get {
                return ResourceManager.GetString("RecoveryPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Curing (Whm spells or equivalent).
        /// </summary>
        internal static string RecoveryPluginTitleAvgCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginTitleAvgCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curing (Whm spells or equivalent).
        /// </summary>
        internal static string RecoveryPluginTitleCuring {
            get {
                return ResourceManager.GetString("RecoveryPluginTitleCuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage Recovery.
        /// </summary>
        internal static string RecoveryPluginTitleRecovery {
            get {
                return ResourceManager.GetString("RecoveryPluginTitleRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +Hide.
        /// </summary>
        internal static string ThiefPluginAndHide {
            get {
                return ResourceManager.GetString("ThiefPluginAndHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string ThiefPluginEventTypeFailed {
            get {
                return ResourceManager.GetString("ThiefPluginEventTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskill.
        /// </summary>
        internal static string ThiefPluginEventTypeWeaponskill {
            get {
                return ResourceManager.GetString("ThiefPluginEventTypeWeaponskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-15}{1,15}{2,10}{3,10}.
        /// </summary>
        internal static string ThiefPluginFormatDataLineLong {
            get {
                return ResourceManager.GetString("ThiefPluginFormatDataLineLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-15}.
        /// </summary>
        internal static string ThiefPluginFormatDataLineShort {
            get {
                return ResourceManager.GetString("ThiefPluginFormatDataLineShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-20}{1,10}{2,20}.
        /// </summary>
        internal static string ThiefPluginFormatSummary1 {
            get {
                return ResourceManager.GetString("ThiefPluginFormatSummary1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-20}{1,30}.
        /// </summary>
        internal static string ThiefPluginFormatSummary2 {
            get {
                return ResourceManager.GetString("ThiefPluginFormatSummary2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,30}{1,20}.
        /// </summary>
        internal static string ThiefPluginFormatSummary3 {
            get {
                return ResourceManager.GetString("ThiefPluginFormatSummary3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0,-20}{1,10}{2,20:f2}.
        /// </summary>
        internal static string ThiefPluginFormatSummaryP {
            get {
                return ResourceManager.GetString("ThiefPluginFormatSummaryP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string ThiefPluginLabelAverage {
            get {
                return ResourceManager.GetString("ThiefPluginLabelAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ThiefPluginLabelCount {
            get {
                return ResourceManager.GetString("ThiefPluginLabelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee:.
        /// </summary>
        internal static string ThiefPluginLabelMelee {
            get {
                return ResourceManager.GetString("ThiefPluginLabelMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Count:.
        /// </summary>
        internal static string ThiefPluginLabelSuccessCount {
            get {
                return ResourceManager.GetString("ThiefPluginLabelSuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Melee:.
        /// </summary>
        internal static string ThiefPluginLabelSuccessfulMelee {
            get {
                return ResourceManager.GetString("ThiefPluginLabelSuccessfulMelee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Total:.
        /// </summary>
        internal static string ThiefPluginLabelSuccessfulTotal {
            get {
                return ResourceManager.GetString("ThiefPluginLabelSuccessfulTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string ThiefPluginLabelTotal {
            get {
                return ResourceManager.GetString("ThiefPluginLabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskills:.
        /// </summary>
        internal static string ThiefPluginLabelWeaponskills {
            get {
                return ResourceManager.GetString("ThiefPluginLabelWeaponskills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        internal static string ThiefPluginMiss {
            get {
                return ResourceManager.GetString("ThiefPluginMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak Attack &amp; Trick Attack.
        /// </summary>
        internal static string ThiefPluginSneakAndTrick {
            get {
                return ResourceManager.GetString("ThiefPluginSneakAndTrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sneak Attack.
        /// </summary>
        internal static string ThiefPluginSneakAttack {
            get {
                return ResourceManager.GetString("ThiefPluginSneakAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Weaponskills.
        /// </summary>
        internal static string ThiefPluginSoloWS {
            get {
                return ResourceManager.GetString("ThiefPluginSoloWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thief.
        /// </summary>
        internal static string ThiefPluginTabName {
            get {
                return ResourceManager.GetString("ThiefPluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trick Attack.
        /// </summary>
        internal static string ThiefPluginTrickAttack {
            get {
                return ResourceManager.GetString("ThiefPluginTrickAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,10}  :  {1,10}.
        /// </summary>
        internal static string WSRatePluginDetailsFormat {
            get {
                return ResourceManager.GetString("WSRatePluginDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       Hits      Frequency.
        /// </summary>
        internal static string WSRatePluginDetailsHeader {
            get {
                return ResourceManager.GetString("WSRatePluginDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}{1,13}{2,10}{3,13}{4,11}{5,11}{6,9:f2}{7,9:f2}{8,9}{9,7}.
        /// </summary>
        internal static string WSRatePluginMainFormat {
            get {
                return ResourceManager.GetString("WSRatePluginMainFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player               # Melee Hits   # Retal.   # WSkills   Min Hits   Max Hits   A.Mean   H.Mean   Median   Mode.
        /// </summary>
        internal static string WSRatePluginMainHeader {
            get {
                return ResourceManager.GetString("WSRatePluginMainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS Rates.
        /// </summary>
        internal static string WSRatePluginTabName {
            get {
                return ResourceManager.GetString("WSRatePluginTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponskill/TP Rates.
        /// </summary>
        internal static string WSRatePluginTitle {
            get {
                return ResourceManager.GetString("WSRatePluginTitle", resourceCulture);
            }
        }
    }
}
